# This is a simple YAML file for a CI/CD pipeline that triggers API testing using Bruno CLI on push to any branch

name: API Testing Workflow

# Defines the event for the workflow
on:
  push:
    branches:
      - '*' # This indicates all branches, adjust as necessary

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Get Current Date and Time
        run: echo "DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Create Output Directory
        run: mkdir -p FrameFiesta/FrameFiesta.Bruno/results

      - name: Run API Testing Collection
        run: |
          cd ./FrameFiesta.Bruno/FrameFiesta-Api-Testing
          bru run . --env baseUrl=${{vars.BASEURL}} --output ../results/${{ env.DATETIME }}_report.json --insecure

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: FrameFiesta/FrameFiesta.Bruno/results
