name: API Testing Workflow

on:
  push:
    branches:
      - '*'

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Get Current Date and Time
        run: echo "DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Create Output Directory
        run: mkdir -p FrameFiesta/FrameFiesta.Bruno/results

      - name: Run API Testing Collection
        run: |
          cd ./FrameFiesta.Bruno/FrameFiesta-Api-Testing
          npm install
          bru run . --env framefiesta_env --output ${{ env.DATETIME }}_report.json --insecure

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: ./results

      - name: Commit results
        run: |
          git config --global user.email "pipeline@example.com"
          git config --global user.name "CI/CD by Paul"
          cd FrameFiesta/FrameFiesta.Bruno/results
          git add .
          git commit -m "Add API Test Results for ${{ env.DATETIME }}" || echo "No changes to commit"
          git push origin HEAD:main
